version: '2'
services:
    mongo:
#        image: mongo:3.0
        image: t2k/mongodb-create
        container_name: mongo-create
#        volumes:
#            - ~/TimeToKnow/mongo:/data/db
        environment:
            - MONGODB_DATABASE=cgs
        ports:
            - 27017:27017
        command: mongod --auth

# connect to mongo and run the user creation scripts manually
# docker exec -it cgs_mongo_1 mongo admin
