version: '2'
services:
    mongo:
        image: t2k/mongodb-create
        container_name: mongo-create
#        network_mode: host
#        volumes:
#            - ~/TimeToKnow/mongo:/data/db
        environment:
            - MONGODB_DATABASE=cgs
        ports:
            - 27017:27017
#        command: mongod --auth