package org.t2k.cgs.domain.usecases.exportimport;

import org.t2k.cgs.domain.model.exceptions.DsException;
import org.t2k.cgs.domain.model.user.CGSUserDetails;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

/**
 * Created by IntelliJ IDEA.
 * User: efrat.gur
 * Date: 23/09/13
 * Time: 14:39
 */
public interface ExportImportService {

    /**
     * Export a course by a given publisher.
     *
     * @param publisherId
     * @param courseId
     * @param jobId       - describes the progress in the jobs table
     * @return String
     * @throws org.t2k.cgs.domain.model.exceptions.DsException
     */
    void exportCourse(int publisherId, String courseId, String jobId, CGSUserDetails cgsUserDetails) throws Exception;

    /**
     * Import a course by a given publisher.
     * @param publisherId
     * @param jobId       - describes the progress in the jobs table
     * @throws org.t2k.cgs.domain.model.exceptions.DsException
     */
    void importCourse(int publisherId, String jobId, String zipFileName, CGSUserDetails cgsUserDetails) throws Exception;

    /**
     * Validate the import - currently compare the export and the import version and verify that the versions match.
     * @param zipFile
     * @param
     * @throws org.t2k.cgs.domain.model.exceptions.DsException
     */
    void validationBeforeImport(String zipFile, String jobId) throws Exception;

    /**
     * @param items - List of FileItems, one of which is a file to upload. The list is typically generated by ServletFileUpload.parseRequest.
     * @param filePath
     * @throws DsException
     */
    String uploadFile(List items, String filePath) throws DsException;

    void downloadExportedCourse(String exportedCourseFileName, HttpServletResponse response) throws IOException;

    void removeOldExportedCoursesFiles(int daysBack) throws IOException;

    String getExportedCoursesLocation();
}